#!/usr/bin/python

import json
import argparse
from store import say, Archive

parser = argparse.ArgumentParser(description='Add a new project to the featured projects.')
parser.add_argument('--url', help='project url', required=True)
parser.add_argument('--title', help='project title', required=True)
parser.add_argument('--tags', help='project tags', required=True)
parser.add_argument('--description', help='project description', required=True)
parser.add_argument('--index', help='index for the project on the grid', type=int, default=0)
args = parser.parse_args()

arch = Archive('projects.json')
arch.add(args.index, [args.url, args.title, args.tags, args.description])

say('Added project {0} at index {1}.'.format(args.title, args.index))


